NASA-PDS/portal-wp

- .github/workflows/secrets-detection.yaml
- .secrets.baseline
- Makefile
- apps/frontend/src/pages/investigations/detail.tsx
- apps/frontend/src/state/slices/instrumentHostsSlice.ts
- apps/frontend/src/state/slices/instrumentsSlice.ts
- apps/frontend/src/state/slices/investigationsSlice.ts
- apps/frontend/src/state/slices/targetsSlice.ts
- apps/frontend/vite.config.ts
The Vite proxy has been updated so that requests for information from the API are fetched from a locally running instance of the registry.  An accept header was also added to all data requests to resolve an error being reported by the API about invalid data type being requested.
Note: this only affects local development.
Verified dev proxy configuration is working by running the dev server locally and ensuring that data could be retrieved from the locally running instance of the registry.
Fixes #11
> Updated Vite Proxy

- apps/frontend/package-lock.json
- apps/frontend/package.json
- apps/frontend/vite.config.ts
-Fixed a bug where running npm run build -> npm run preview would throw useState useContext errors.
Run as usual in the readme but use this branch along with https://github.com/NASA-PDS/wds-react/tree/bugs/fix-parent-preview branch in wds-react.
Also need to run "npm install -D @types/node" on this repo. Or npm install
https://github.com/NASA-PDS/wds-react/pull/61
https://github.com/NASA-PDS/portal-wp/issues/19
> Fix Deployment Preview Bug #19

- apps/frontend/vite.config.ts
Added leading slash to 'base' configuration in vite.config.ts to resolve ""base" option should start with a slash." warning being reported when using `npm run preview`.
Local builds and preview do not generated errors or warnings.
#35
> Update vite configuration to resolve warning

- README.md
This PR addresses updates to the README that now includes steps to build the portal-wp codebase. These steps are listed under the heading of "Manual Deployments".
-
#40
> Update README with code building instructions

- apps/frontend/src/pages/search/index.tsx
- apps/frontend/src/pages/search/searchUtils.ts
Added facility, telescope and instrument host to search result types.
Run with wds-react https://github.com/NASA-PDS/wds-react/pull/66 Do a search for "telescope" you will see telescope, facility and instrument_host types in the results.
resolves https://github.com/NASA-PDS/portal-wp-tasks/issues/109
> Add More Search Result Types To Search Page

- apps/frontend/package-lock.json
- apps/frontend/package.json
This PR addresses the need to update the `package*.json` files to include the `use-debounce` package.
Test builds did not produce any errors.
#48
> Update package*.json files

- apps/frontend/src/pages/search/index.tsx
- apps/frontend/src/pages/search/searchUtils.ts
- apps/frontend/src/types/solrSearchResponse.d.ts
All the search page result links now link to a page. Added resource search result type.
Run normally. Search for something on the search page. Click on results.
resolves https://github.com/NASA-PDS/portal-wp-tasks/issues/112
> Add Search Page Result Links

- apps/frontend/src/pages/search/index.tsx
This PR addresses the fix needed to link to a valid tab on the investigations page from the search results page.
Tested fix locally.
#72
> Fix search result linking for investigations

- apps/frontend/src/pages/search/index.tsx
Fixes a bug where titles were showing the entire contents of an array instead of only the first item in the array.
Run normally as instructed in the read me.
> Fix Search Result Title Display

- apps/frontend/src/components/HomeSearch/HomeSearch.scss
- apps/frontend/src/components/HomeSearch/HomeSearch.tsx
- apps/frontend/src/pages/search/index.tsx
- apps/frontend/src/pages/search/searchUtils.ts
- apps/frontend/src/types/solrSearchResponse.d.ts
This Pull request changes facets to use the title value for display instead of the name which is sometimes missing. 
It also adds a style to wrap facet names in the home page drop downs.
Run this branch normally as stated in the read me. Observe the facet drop downs in the home page and the facet names in the search page.
fixes #68
> Use Facet Titles Instead Of Names #68

- apps/frontend/src/components/Filters/Filter.tsx
- apps/frontend/src/components/Filters/filter.scss
- apps/frontend/src/pages/search/index.tsx
- apps/frontend/src/pages/search/searchUtils.ts
- apps/frontend/src/types/solrSearchResponse.d.ts
This PR adds filter counts for each filter option in the search page.
Run normally.
Observe the filter count number next to each filter option in the search page.
fixes #69
> Show Facet Counts In Search Page Filters

- apps/frontend/src/components/IndexedListComponent/InvestigationsIndexedListComponent.tsx
Updated the investigations directory page so that the spacecraft listings for each Investigation are sorted alphabetically.
Tested locally and ensured `npm run build` does not generated errors.
Fixes #104
> Sorted Spacecraft list alphabetically for each Investigation on the Investigation's directory page.

- apps/frontend/src/AppConfig.ts
- apps/frontend/src/layouts/RootLayout.tsx
Added a banner message to the site using the newly created banner component so that users are informed that they are browsing a beta version of the site.
Companion PR containing banner component: https://github.com/NASA-PDS/wds-react/pull/77
Tested locally and ensured that no errors are present when `npm run build` is executed.
Fixes #90
> Add banner message to website to indicate to users that the site they are viewing is in beta

- apps/frontend/src/components/Banner/SolrWarningBanner.tsx
- apps/frontend/src/layouts/RootLayout.tsx
This PR adds a warning when solr returns an error or no results on the home and search page.
Edit the SolrWarningBanner.tsx file to point to a non existent URL. Run normally and go to the home or search page. The error banner will appear.
fixes #71
> Add Solr Warning #71

- apps/frontend/src/components/IndexedListComponent/InstrumentsIndexedListComponent.tsx
- apps/frontend/src/components/IndexedListComponent/InvestigationsIndexedListComponent.tsx
- apps/frontend/src/components/StatsList/StatsItem.tsx
- apps/frontend/src/components/StatsList/StatsList.tsx
- apps/frontend/src/pages/instruments/detail.tsx
- apps/frontend/src/pages/search/index.tsx
- apps/frontend/src/utils/links.ts
This PR addresses the following:
* Updated the investigation title stats item on the instrument detail page in the header so that it is now a link that can navigate a user to the respective investigation detail page
* Added new "links" utility to centralize the location of functions to assist with generating links throughout the portal.
* Updated investigation and instrument directory pages to use newly added link utility functions
* Removed unneeded code and import statements due to addition of links utility functions.
Tested locally and ensured that `npm run build` does not generate any errors.
Fixes #117
> Updated investigation title on instrument detail page so that it is a link that can navigate a user to the respective investigation detail page.

- apps/frontend/src/components/HomeSearch/HomeSearch.scss
- apps/frontend/src/components/HomeSearch/HomeSearch.tsx
Search text in the search bar and the selected filters are kept in the URL history. Once a new page is opened the back button will reload the changes. A link can also be saved to be reopened later.
Updated some minor css on the home page search.
Run with https://github.com/NASA-PDS/wds-react/pull/79. Test the home page by making some selections or typing something in the search box. Click on search or click on a link. Press the back button. The page will load as it was before.
fixes #97 
references https://github.com/NASA-PDS/wds-react/pull/79
> Add ability to maintian history of navigated pages when the search feature is used in the header.

- apps/frontend/src/pages/home/index.tsx
MRO and LRO are now spelled out on the home page investigations list.
Run normally. The investigation list items for MRO and LRO will now be spelled out.
fixes #125
> Spell Out MRO LRO On Home Page #125

- apps/frontend/src/components/Filters/Filter.tsx
- apps/frontend/src/components/Filters/Filters.tsx
- apps/frontend/src/components/Filters/filter.scss
- apps/frontend/src/pages/search/index.tsx
- apps/frontend/src/pages/search/searchUtils.ts
- apps/frontend/src/types/solrSearchResponse.d.ts
This pull request changes to how the filters work on the search page in the following ways:
- Added variants for the filter component to have a single and multi select.
- Filters are now frozen from the point in that they were set. Order is determined by which one is first in the url.
- Solr queries for the filters have been updated.
- Filter titles now show in alphabetical order.
@jordanpadams @anilnatha This pull request requires updating solr in order to work. The titles must be single value not array or else it will only show the first letter. 
Run normally with the develop branch of wds-react. Click on the check boxes in search. The test scenario is outlined in https://github.com/NASA-PDS/portal-wp/issues/119 
- fixes #119 
- fixes #129 
- refs …
> Improve Search Filtering #119

- apps/frontend/src/pages/search/index.tsx
- apps/frontend/src/types/solrSearchResponse.d.ts
This pull request updates the page type value that is shown in the search results details to the correct value.
Run normally. All search results will match their data type with the filter label.
fixes #139
> Update Search Result Page Type Label #139

- apps/frontend/src/components/HomeSearch/HomeSearch.tsx
- apps/frontend/src/pages/search/index.tsx
- apps/frontend/src/pages/search/searchUtils.ts
- apps/frontend/src/types/solrSearchResponse.d.ts
- apps/frontend/src/types/solrSearchResponseExpected.d.ts
As solr is being developed some types change between strings or string arrays. This pull request adds an expected type that the client will expect from solr. It will then convert all values to arrays and use that type instead. This way it won't break the client due to unexpected type if solr types suddenly change.
Run normally. All values will look the same. Tested build process is successful.
fixes #137
> Add Solr String To String Array Flexibility #137

- apps/frontend/src/components/Filters/Filter.tsx
- apps/frontend/src/components/Filters/Filters.tsx
- apps/frontend/src/pages/search/index.tsx
- apps/frontend/src/pages/search/searchUtils.ts
- apps/frontend/src/types/solrSearchResponse.d.ts
- apps/frontend/src/types/solrSearchResponseExpected.d.ts
-Removed checkboxes from single select filters. The text is now clickable instead of the checkbox.
-When a single filter is selected the options list becomes hidden. 
-Filter title has been added to the selected filter chip.
Run normally with wds-react develop branch. Build tested and runs without issue.
fixes #141
> Remove Checkbox From Single Select Filters #141

- apps/frontend/src/components/Banner/SolrWarningBanner.tsx
- apps/frontend/src/pages/search/index.tsx
- apps/frontend/src/pages/search/search.css
This PR makes it so that If the search service fails the search page will show an error message. This will replace the infinite loading icon.
Run normally with wds-react develop branch. To test: set the network to off or change the service url to a non-existent one in order to produce an error during the fetch service call. 
fixes #138
> Show Search Error #138

- apps/frontend/src/pages/search/index.tsx
This PR makes it so that Datasets, bundles, collections, targets, telescopes, facilities, and resources all link to the resLocation value.
product_class:Product_Data_Set_PDS3 corresponds to “dataset” (now points to resLocation)
product_class:Product_Bundle corresponds to “product_bundle” (already set to resLocation)
product_class:Product_Collection corresponds to datacollection (already set to resLocation)
Search Examples:
Dataset: NEW HORIZONS ALICE JUPITER ENCOUNTER V2.0
Bundle: BUS-DEMEO ASTEROID TAXONOMY
Datacollection: Collection of raw products: Mascot Mara
Others that previously were pointing to dsview:
Target = product_class:product_context && data_class:target
Telescope = product_class:product_context && data_class:telescope
Facility = product_class:product_context && …
> Use resLocation For Linking Search Results #147

- apps/frontend/src/pages/instruments/detail.tsx
This PR Fixes an issue where the instrument page attempting to load investigation link before it was loaded.
Run normally with wds-react develop branch. Go directly to an instrument page for example: `http://localhost:5173/portal/instruments/urn--jaxa--darts--context--instrument--vco---ir1/data`
fixes #156
> Fix Direct Instrument Page Load Error #156

- .secrets.baseline
- apps/frontend/.env/.env
- apps/frontend/package.json
- apps/frontend/src/AppConfig.ts
- apps/frontend/src/components/Footer/Footer.tsx
- apps/frontend/src/components/Header/Header.tsx
- apps/frontend/src/pages/home/index.tsx
- apps/frontend/src/pages/instruments/detail.tsx
- apps/frontend/src/pages/investigations/detail.tsx
- apps/frontend/src/pages/search/index.tsx
Updated env and app configuration so that our support email address can be stored in one place and referenced wherever it is needed. Also fixed the email address displayed to users when a search error occurs using this centralized email address.
Since this change affects our secrets, I also updated and audited our secrets baseline to squash previously reported errors by our GH secrets detection workflow.
Tested by running codebase locally and verified that production cold builds do not generate an error.
- Fixes #142
- Fixes #161
> Fixed email address for search page and updated secrets baseline

- apps/frontend/src/components/HomeSearch/HomeSearch.tsx
- apps/frontend/src/pages/search/index.tsx
This pull request fixes an issue where searching for strings that contain slashes would cause a 404.
Run normally with wds-react develop branch. Search for CASSINI SS/S RPWS DERIVED LANGMUIR PROBE SWEEP V1.0, CO-SS/S-RPWS-5-LPSWEEP-V1.0 in the home page and search page. It will no longer return a 404.
fixes #145
> Fix Search String With Slash #145

- apps/frontend/package-lock.json
- apps/frontend/package.json
- apps/frontend/src/components/Footer/Footer.tsx
This PR addresses:
- bumped `@nasapds/wds-react` to `0.0.6`
- updated last updated date value in footer
- bumped `portal-wp` package version to `0.0.7`
Tested locally and verified that no build errors were generated by `npm run build`.
> Bumped @nasapds/wds-react version and updated site's last updated date.
